import React from "react";
import Link from "next/link";

const TermsOfService = () => {
  return (
    <main className="flex justify-center py-24 px-6 bg-muted/10">
      <div className="w-[70%] flex flex-col gap-16">

        {/* Header */}
        <div className="flex flex-col gap-6">
          <h1 className="text-5xl font-semibold">
            Terms of <span className="text-element">Service</span>
          </h1>
          <p className="text-lg text-muted-foreground">
            Last updated: January 2026
          </p>
          <div className="h-[3px] w-20 bg-element rounded-full"></div>
        </div>

        {/* Content */}
        <div className="flex flex-col gap-10 text-lg leading-relaxed">

          <p>
            Welcome to <span className="font-semibold text-element">Listiq</span>.
            By accessing or using our platform, you agree to comply with and be
            bound by the following Terms of Service.
          </p>

          {/* Section */}
          <div className="flex flex-col gap-4">
            <h2 className="text-2xl font-semibold">1. Use of Service</h2>
            <p>
              Listiq provides AI-generated product listing content tailored for
              e-commerce marketplaces. You agree to use the platform only for
              lawful business purposes.
            </p>
            <p>
              You are responsible for ensuring that the content you publish
              complies with marketplace rules and applicable laws.
            </p>
          </div>

          {/* Section */}
          <div className="flex flex-col gap-4">
            <h2 className="text-2xl font-semibold">2. No Ranking Guarantee</h2>
            <p>
              While Listiq generates SEO-optimized listings based on structured
              inputs and marketplace logic, we do not guarantee product ranking,
              visibility, sales performance, or algorithmic placement on any
              marketplace.
            </p>
          </div>

          {/* Section */}
          <div className="flex flex-col gap-4">
            <h2 className="text-2xl font-semibold">3. AI-Generated Content</h2>
            <p>
              Content generated by our AI system may contain inaccuracies,
              omissions, or unintended similarities. You are solely responsible
              for reviewing, editing, and approving content before publishing.
            </p>
          </div>

          {/* Section */}
          <div className="flex flex-col gap-4">
            <h2 className="text-2xl font-semibold">4. Credits & Payments</h2>
            <p>
              Listiq operates on a credit-based system. Each listing generation
              consumes credits from your account balance.
            </p>
            <p>
              All credit purchases are final and non-refundable unless
              explicitly stated otherwise.
            </p>
          </div>

          {/* Section */}
          <div className="flex flex-col gap-4">
            <h2 className="text-2xl font-semibold">5. Account Responsibility</h2>
            <p>
              You are responsible for maintaining the confidentiality of your
              account credentials and for all activities conducted under your
              account.
            </p>
          </div>

          {/* Section */}
          <div className="flex flex-col gap-4">
            <h2 className="text-2xl font-semibold">6. Limitation of Liability</h2>
            <p>
              Listiq shall not be liable for any direct, indirect, incidental,
              or consequential damages resulting from the use of our platform,
              including but not limited to lost revenue, ranking changes, or
              marketplace penalties.
            </p>
          </div>

          {/* Contact Section */}
          <div className="flex flex-col gap-4">
            <h2 className="text-2xl font-semibold">7. Contact</h2>
            <p>
              If you have any questions regarding these Terms, please contact
              us via our{" "}
              <Link href="/contact" className="text-element font-medium underline">
                Contact Page
              </Link>.
            </p>
          </div>

        </div>

      </div>
    </main>
  );
};

export default TermsOfService;